name: Pages
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: ros:humble
    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
        path: main
    - name: Apt update
      run: sudo apt-get update
    - name: Install doxygen
      run: sudo apt-get install -y doxygen
    - name: Build and Commit
      uses: javilinos/pages@v2
      with:
        aerostack2_modules: [python_interface, as2_core]
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        directory: main
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
