name: Pages
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ros:humble
    steps:
    - uses: actions/setup-python@v2
    - uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
        path: main
    - uses: actions/checkout@master
      with:
        repository: javilinos/python_interface
        ref: 1-documentation
        path: python_interface
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Build and Commit
      uses: javilinos/pages@v2
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        directory: main
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
